### ISSUE TITLE
request: Workspace headers/metadata.

### ISSUE THREAD

**Issue by shanna** [rogchap/wombat#1]
Our gRPC endpoints currently use a combination of TLS and oauth2 bearer tokens so support for additional headers without mutual TLS would allow us to authenticate with Wombat.

**Comment by rogchap** [comment]
You can already add additional metadata headers to the requests via the "metadata" tab. Just add your "authorization" key with your "bearer" token as the value .

**Comment by nycnewman** [comment]
I was testing this yesterday but wombat fails silently (I know from README you are working on this). From a UI perspective it might be good to move some (all?) headers to Connection settings. I was testing TLS with mutual auth with a Bearer token and I find it confusing that you go into TLS settings and then don't connect and then add Header and then finally send. May be cause of failure if it expects connection already up. But I have an authenticated GRPC API which requires both mTLS and Bearer token.

**Comment by rogchap** [comment]
Thanks for providing this feedback.

I'm a little confused on the requirements:
Are you needing to send Headers/Metadata on the initial connection rather than per RPC?

Client cert/key is already supported, and you can then add Metadata on every RPC request. Is mTLS not working?

I think I'm missing something in your setup.

**Comment by nycnewman** [comment]
Headers for every connection / call to service. Can't test mTLS as program dies silently before any connection or response. Equivalent in grpcurl is to pass certificate and Bearer token as parameters to call including reflection.
