### ISSUE TITLE
Add support for multiple workspaces

### ISSUE THREAD

**Issue by jack1902** [rogchap/wombat#11]
Similar to how Insomnia lays out multiple pre-defined requests. Provide the ability to have requests sit on their own, or be grouped within a folder.

This is a major usability piece as working on multiple endpoints over time will get very tedious to keep updated Wombat

<img width="240" alt="Screenshot 2020-11-11 at 09 28 32" src="https://user-images.githubusercontent.com/39212456/98793786-461f7a00-2400-11eb-8737-1828efe8ef1c.png">

**Comment by rogchap** [comment]
Thanks for raising. Yes, I plan on adding support for Workspace switching. 

Just an FYI: In my environment I have lots of gRPC microservices; so I use Envoy (with docker-compose) to act as a proxy to all the services via one address and just setup some routes to the other services in the envoy config. This way I can bring all my services into the default workspace (just an idea for you).
