### ISSUE TITLE
UI in windows is broken

### ISSUE THREAD

**Issue by k1ng440** [rogchap/wombat#14]
Please see 

https://puu.sh/GMq7x/cbc5aa786a.png

**Comment by ecriminal** [comment]
Same issue for me

**Comment by wahmedswl** [comment]
Yup, On windows 10 and same issue.

**Comment by rogchap** [comment]
Let me know if you have more joy with v0.2.2.
I have to admit that I'm not a Windows user; testing on a VM is painful
