### ISSUE TITLE
Feature Request: Multi Environment Workspace

### ISSUE THREAD

**Issue by xitonix** [rogchap/wombat#22]
First of all, fantastic work guys. Thank you. 🏅  

I was thinking it would have been great if we could label workspaces and have a dropdown in the UI to switch between different workspaces (environments). It would also be useful to be able to choose where the workspaces are stored on the disk.

Keep up the good work fellas.

**Comment by rogchap** [comment]
Thanks for the feedback; and the kind words.

100% agree; I plan on adding multiple workspaces and easy workspace switching. Hopefully not too far in the future (few bugs I need to take care of first).

**Comment by rogchap** [comment]
#11

**Comment by rogchap** [comment]
I'm closing this and will track this feature against #11 
If you feel this is a different feature request, please re-open.
Thanks again for the suggestion.

**Comment by xitonix** [comment]
Thanks @rogchap . Sounds good to me mate :)
