### ISSUE TITLE
Build instructions would make testing contributions easier

### ISSUE THREAD

**Issue by nycnewman** [rogchap/wombat#3]
After fighting for a couple of days with Go / Qt / etc it would be really helpful to have a short description of the requirements / dependencies for this project and the build steps to create a DMG. This will make testing of branches easier rather than waiting for new releases. Can't test your latest PR as I have yet to successfully build the tool through to a DMG. Apologies.

**Comment by nycnewman** [comment]
Potentially related but currently "go build" dies with:

# rogchap.com/wombat/internal/model
internal/model/input.go:59:3: i.SetRoles undefined (type *Message has no field or method SetRoles)
internal/model/input.go:72:3: i.SetEnabled undefined (type *Message has no field or method SetEnabled)
internal/model/input.go:79:3: i.ConnectUpdateFieldValue undefined (type *Message has no field or method ConnectUpdateFieldValue)
internal/model/input.go:87:25: i.Fields undefined (type *Message has no field or method Fields)
internal/model/input.go:91:11: i.Fields undefined (type *Message has no field or method Fields)
internal/model/input.go:117:14: i.Fields undefined (type *Message has no field or method Fields)
internal/model/input.go:125:10: i.Roles undefined (type *Message has no field or method Roles)
internal/model/input.go:129:8: i.Fields undefined (type *Message has no field or method Fields)
internal/model/keyval_list.go:41:3: m.SetRoles undefined (type *KeyvalList has no field or method SetRoles)
internal/model/keyval_list.go:51:3: m.ConnectValAt undefined (type *KeyvalList has no field or method ConnectValAt)
internal/model/keyval_list.go:51:3: too many errors

**Comment by rogchap** [comment]
Thanks for the feedback @nycnewman.
Agree that this would be beneficial; even for my own memory! The Go / Qt / modules / vendor folder etc is a bit complex.
I will add details in the coming weeks. 
the issue you are facing above is the there is a whole load of Go files that are auto-generated by `qtmoc  desktop`

**Comment by nycnewman** [comment]
New Beta works. Thanks. I eventually made some progress with Qt build process but still sadly not working yet.

Utility now works better and can pull schema from GRPC service and allows me to test against various endpoints. Died without error when passing bad parameters though.

**Comment by rogchap** [comment]
Due to a lack of productivity with Qt and slow build times, I've decided to scrap Qt and have rebuilt everything from the ground up using [Wails](https://github.com/wailsapp/wails). 

This should make everything easier; will still add some docs on how to get started etc once I have the new version released (0.2.0 🔜), but going to close this issue for now.
