### ISSUE TITLE
oneof fields with only one option block the UI

### ISSUE THREAD

**Issue by Horneth** [rogchap/wombat#31]
I have an edge case with a `oneof` field with only one possible value, like:

```proto
message Bar {
}

message Foo {
  oneof value {
    Bar bar = 1;
  }
}
```

`bar` does show up in the dropdown but when I select it, the UI gets in a strange state where everything is either unresponsive or pressing buttons doesn't have any effect. `oneof` with several options work fine. This is on `0.3.2`, I don't recall having this problem on `0.2.0`. I'm on Mac if that matters.

**Comment by rogchap** [comment]
Thanks for reporting; will take a look at what causes this.
