### ISSUE TITLE
Repeated uint32 not working on gui

### ISSUE THREAD

**Issue by JoaoSobral** [rogchap/wombat#36]
Hi,

Wombat interface does not let me expand the "objID" (see picture below) this is an array of uint32.
![Screenshot 2020-12-13 at 02 22 29](https://user-images.githubusercontent.com/2829936/102000693-5d48d480-3cea-11eb-85ca-d136151f5b63.png)

Proto
![Screenshot 2020-12-13 at 02 22 52](https://user-images.githubusercontent.com/2829936/102000706-718cd180-3cea-11eb-95d1-2389b98b3f73.png)

**Comment by rogchap** [comment]
Hey @JoaoSobral; thanks for reporting.

I don't think this is an issue with uint32 directly; as it works for me:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/270252/102005049-f3700f80-3d69-11eb-86ff-6523a960d462.png">

What is being displayed in the GUI (Wombat) does not appear to match the Proto file 🤔 : your proto is showing that `objID` is a `repeated uint32` but Wombat is showing `repeated protobuild.servicebusinness.Organisation`; are you sure you are parsing the right set of proto files?

Your bug may be related to  similar bug I found that would reset/loose the state between changing methods for oneof fields that contained repeated values, that could cause the "add" on repeated fields to become unresponsive (which I think is happening in your case).

I think I have solved this with #37 🤞

**Comment by JoaoSobral** [comment]
Hi,

I double check and I am parsing the right proto. Same situation happens with Organisationset (repeated organisations).  Try this behaviour -> organisationservice (create) and add organisations (will work) -> (delete) and add organisations (will fail) -> go back to create (will fail). Change service to processservice and cameback to organisationservice (create) will work. Concerning delete never worked. I will send the proto via email to you.

**Comment by rogchap** [comment]
Thank you for sending the proto file. Wow.... bad bug.
I was able to replicate your issue with your proto file with v0.3.2; the good news that I also tried with #37 and it fixes it. 
There are just a few label problems that I still need to fix but nothing major.

**Comment by rogchap** [comment]
@JoaoSobral  I've just released [v0.3.3](https://github.com/rogchap/wombat/releases/tag/v0.3.3); let me know if that resolves your issues.

Thanks again for reporting.

**Comment by JoaoSobral** [comment]
Working good @0.3.3! Thanks for been fast.
