### ISSUE TITLE
Hard to open macOS build

### ISSUE THREAD

**Issue by foisonocean** [rogchap/wombat#4]
wombat build: Wombat_0.1.0-beta.1_Darwin_x86_64.dmg
macOS version: 10.15.6 (19G2021)

I just tried 2 ways to open wombat, open it directly in the dmg file, or drag the application to `/Applications` folder and then open it from `/Applications` folder.

1. Open it directly from the dmg container without dragging it to `/Applications` folder.

<img width="624" alt="CleanShot 2020-09-24 at 11 21 00@2x" src="https://user-images.githubusercontent.com/15059605/94097179-9a729880-fe58-11ea-8def-3345a9cb3d08.png">

Later on I got this warning:

<img width="488" alt="CleanShot 2020-09-24 at 11 20 49@2x" src="https://user-images.githubusercontent.com/15059605/94097493-2d133780-fe59-11ea-915a-aaf9cf19c048.png">

I can ignore it and change settings in `System Preferences / Security & Privacy` and finally can open it, but it's annoying because I have to open it from dmg container directly.

2. Drag wombat to `/Applications` folder and then open it from `/Applications` folder

The Icon of wombat becomes broken in `/Applications` folder

![CleanShot 2020-09-24 at 11 21 25@2x](https://user-images.githubusercontent.com/15059605/94097723-a1e67180-fe59-11ea-8460-3475a4a67c66.png)

When I try to open it, I got this error message:

<img width="532" alt="CleanShot 2020-09-24 at 11 22 05@2x" src="https://user-images.githubusercontent.com/15059605/94097102-66977300-fe58-11ea-9dbe-15c76a1a882d.png">

Even if I changed the settings of `System Preferences / Security & Privacy`, I can not open wombat from `/Applications` folder eventually.

**Comment by rogchap** [comment]
As per the README: you need to right (option) click the app and select "open". 
This is because Apple want you to pay them money to sign the application and be a registered developer so that this does happen for users.
As this is pre-release, I'm not giving Apple a cent until I validate that people are keen on using this tool.
