### ISSUE TITLE
Support add metadata to grpc request

### ISSUE THREAD

**Issue by yswtrue** [rogchap/wombat#47]
now the metadata only support for reflaction API, but jwt auth need token from metadata hope, add support for it. Thanks.

**Comment by rogchap** [comment]
This is already supported by using the `Metadata` tab in the Request panel:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/270252/105132940-e4863500-5b3f-11eb-81ae-da91d15e6dbc.png">
