### ISSUE TITLE
Export/Import request to/from grpcurl

### ISSUE THREAD

**Issue by devkanro** [rogchap/wombat#50]
Sometimes I need to share my request settings/metadata with my team.
I will export a curl command for other people, they can import the curl command in PostMan or other something in HTTP/Json case.

Maybe we can support export and import request to grpcurl?

```Shell
grpcurl -d '{"id": 1234, "tags": ["foo","bar"]}' \
    grpc.server.com:443 my.custom.server.Service/Method
```

**Comment by rogchap** [comment]
Thanks for the suggestion; will look into this.

**Comment by devkanro** [comment]
I and my teammate(@iou90) have forked the repo and working on this, we will create a pull request later.

**Comment by fleytman** [comment]
Hi, grpcurl dosn't correct work, if use protofiles on server without reflection. If run from wombat, I get message
```Error invoking method ".../Create": failed to query for service descriptor "...Service": server does not support the reflection API```
If add -proto and -import-path with paths to grpcurl from wombat, I get correct response

@devkanro do you can fix it?

**Comment by devkanro** [comment]
@fleytman This is a known limit, see the PR #51, not sure if this project is still being maintained.

The reason why I didn't support exporting the proto root directory at the time was that I considered the usage scenario of our teamwork. In most cases, my colleague got the exported grpcurl and directly imported his wombat.

I sent grpcurl to another colleague, but on his computer there's a good chance our proto root is in a different location, so exporting the proto root is just a distraction for us.

**Comment by fleytman** [comment]
Thanks for answer, my case if i copy/paste in terminal i get error. And if i get curl with wrong path, my colleague, he can fix path and not need known, which option he need add to grpcurl. And you can clone repo in ~/myrepo. I think, if it add how option, you can use with collegue:
1. You share grpcurl without path
2. He copy from wombat with path and easy execute command

> not sure if this project is still being maintained.

What you use how alternative?

**Comment by devkanro** [comment]
@fleytman 
I am using built in gRPC client in my [IDEA protobuf plugin](https://github.com/devkanro/intellij-protobuf-plugin).

<img width="465" alt="截屏2022-09-05 11 12 58" src="https://user-images.githubusercontent.com/9367842/188353678-e4b3e3c7-a487-4198-9d88-d5e90801a2f7.png">

The official protobuf plugin and gRPC plugin [support this feature](https://blog.jetbrains.com/idea/2021/10/intellij-idea-2021-3-eap-6-enhanced-http-client-kotlin-support-for-cdi-and-more/) too, but it can't import protos in library with Java project.

And you can easy to generate request with line marker in proto.

<img width="380" alt="截屏2022-09-05 11 15 28" src="https://user-images.githubusercontent.com/9367842/188353914-47a29721-6b14-4f2d-9dfd-11c81c0d2dd1.png">

But it can't export as grpcurl, it using a DSL language designed by jetbrains.
