### ISSUE TITLE
Wombat flashes and crashes while installing in Win 10

### ISSUE THREAD

**Issue by kp2202** [rogchap/wombat#58]
I have downloaded Wombat_v0.4.0_Windows_x86_64 from the repo and when I  clicked on the application file, it goes through windows defender smartscreen, when clicked on run anyway, the application flashes n crashes .
 Could you please help me with this.

**Comment by rogchap** [comment]
This is the first report of not being able to install on Windows. 
Can you see if there is a crash.log file in your `C:\Users\[Username]\AppData\Roaming\Wombat`?

**Comment by kp2202** [comment]
Hi,
I looked into the path mentioned by  you.There is no crash.log file however ,there were 3 files ,i deleted them and tried to launch wombat again and it worked.

Thanks for the help :)
