### ISSUE TITLE
Mac build does not run on Mac OSX 10.14

### ISSUE THREAD

**Issue by rogchap** [rogchap/wombat#7]
There are no features that specifically require 10.15, but we are using GitHub Actions to create the build and the default VM is 10.15.
Check to see if we can do a build for 10.14.

**Comment by rogchap** [comment]
Seems like this is not possible using GutHub Actions for the VM build.
```
The macOS virtual environment has been updated to Catalina (v10.15). Please update your workflow and change the line 'runs-on: macOS-10.14' to 'runs-on: macOS-latest'
```
https://github.com/rogchap/wombat/actions/runs/357091342

Closing for now, as I don't think this effects many users. If this is a problem for you, please let me know; I'll re-open and research more into another provider (Does TravisCI or CircleCI support 10.14?)

**Comment by arzonus** [comment]
Hello!
I've got the error when I'm trying to run all Wombat versions since 0.2.0 (maybe earlier). 
![image](https://user-images.githubusercontent.com/4450829/109427286-a3473780-79bf-11eb-99ac-0e4babf2365d.png)

Could you add OSX 10.14 support?
