### ISSUE TITLE
Wombat crashes on macOS Ventura

### ISSUE THREAD

**Issue by rvadaga** [rogchap/wombat#99]
I'm on macOS Ventura 13.1 and have the latest release installed `0.5.0`. When I try to open the application, it crashes without any error messages.

So I ran it from my command line. Here's the complete log along with the relevant dependency versions I have locally https://gist.github.com/rvadaga/94d80922ce012b379f7145c5312449e4

I also deleted the existing application from `/Applications/` and reinstalled it both via DMG file and `brew install --cask wombat`. Neither seems to help. Also tried emptying `rm -rf ~/Library/Application\ Support/Wombat/`

Not a `Go` expert, so I'm not sure what's going wrong. Can someone please look into this? Thanks.

**Comment by Firanus** [comment]
I'm also experiencing this. Would love it if this could get some attention, though it looks like support for Wombat might have fallen off. 😢

**Comment by stevenzyang** [comment]
Works for me after updating to 13.2.1

**Comment by rvadaga** [comment]
Same! Works for me on 13.2.1

**Comment by yelsayd** [comment]
where can I find 13.2.1? the highest published release seems to be 0.5.0.

**Comment by rvadaga** [comment]
@yebrahim 13.2.1 is referring to the macOS version, wombat is still at 0.5.0

**Comment by yelsayd** [comment]
gotcha, yeah that makes sense, thanks.
